ss = 2; ll = 2;

poissSpikeCount = [squeeze(mean(mean(miPoiss.SpikeCount(ss, ll, :, lowIdx)))), ...
    squeeze(mean(mean(miPoiss.SpikeCount(ss, ll, :, midIdx)))), ...
    squeeze(mean(mean(miPoiss.SpikeCount(ss, ll, :, highIdx))))];
poissWords = [squeeze(mean(mean(miPoiss.Words(ss, ll, :, lowIdx)))), ...
    squeeze(mean(mean(miPoiss.Words(ss, ll, :, midIdx)))), ...
    squeeze(mean(mean(miPoiss.Words(ss, ll, :, highIdx))))];
poissSpikeCountStd = [squeeze(std(mean(miPoiss.SpikeCount(ss, ll, :, lowIdx))))/sum(lowIdx), ...
    squeeze(std(mean(miPoiss.SpikeCount(ss, ll, :, midIdx))))/sum(midIdx), ...
    squeeze(std(mean(miPoiss.SpikeCount(ss, ll, :, highIdx))))/sum(highIdx)];
poissWordsStd = [squeeze(std(mean(miPoiss.Words(ss, ll, :, lowIdx))))/sum(lowIdx), ...
    squeeze(std(mean(miPoiss.Words(ss, ll, :, midIdx))))/sum(midIdx), ...
    squeeze(std(mean(miPoiss.Words(ss, ll, :, highIdx))))/sum(highIdx)];

neuralSpikeCount = [squeeze(mean(miNeural.SpikeCount(ss, ll, lowIdx))), ...
    squeeze(mean(miNeural.SpikeCount(ss, ll, midIdx))), ...
    squeeze(mean(miNeural.SpikeCount(ss, ll, highIdx)))];
neuralWords = [squeeze(mean(miNeural.Words(ss, ll, lowIdx))), ...
    squeeze(mean(miNeural.Words(ss, ll, midIdx))), ...
    squeeze(mean(miNeural.Words(ss, ll, highIdx)))];
neuralSpikeCountStd = [squeeze(std(miNeural.SpikeCount(ss, ll, lowIdx)))/sum(lowIdx), ...
    squeeze(std(miNeural.SpikeCount(ss, ll, midIdx)))/sum(midIdx), ...
    squeeze(std(miNeural.SpikeCount(ss, ll, highIdx)))/sum(highIdx)];
neuralWordsStd = [squeeze(std(miNeural.Words(ss, ll, lowIdx)))/sum(lowIdx), ...
    squeeze(std(miNeural.Words(ss, ll, midIdx)))/sum(midIdx), ...
    squeeze(std(miNeural.Words(ss, ll, highIdx)))/sum(highIdx)];

figure;
subplot(1,2,1)
errorbar(poissSpikeCount, neuralSpikeCount, poissSpikeCountStd, 'horizontal', ...
    'k', 'LineWidth', 1.5)
hold on
errorbar(poissSpikeCount, neuralSpikeCount, neuralSpikeCountStd, ...
    'k', 'LineWidth', 1.5)
plot(poissSpikeCount(1), neuralSpikeCount(1), 'o', 'MarkerFaceColor', rgb('Red'), ...
    'MarkerEdgeColor', 'k', 'MarkerSize', 15)
plot(poissSpikeCount(2), neuralSpikeCount(2), 'o', 'MarkerFaceColor', rgb('Yellow'), ...
    'MarkerEdgeColor', 'k', 'MarkerSize', 15)
plot(poissSpikeCount(3), neuralSpikeCount(3), 'o', 'MarkerFaceColor', rgb('Green'), ...
    'MarkerEdgeColor', 'k', 'MarkerSize', 15)
xlabel('Poisson'); ylabel('Neural'); title('Spike Count')
box off; axis square;
rf = refline(1,0); rf.Color = rgb('DarkGrey'); rf.LineStyle = '--'; rf.LineWidth = 1;

subplot(1,2,2)
errorbar(poissWords, neuralWords, poissWordsStd, 'horizontal', ...
    'k', 'LineWidth', 1.5)
hold on
errorbar(poissWords, neuralWords, neuralWordsStd, ...
    'k', 'LineWidth', 1.5)
plot(poissWords(1), neuralWords(1), 'o', 'MarkerFaceColor', rgb('Red'), ...
    'MarkerEdgeColor', 'k', 'MarkerSize', 15)
plot(poissWords(2), neuralWords(2), 'o', 'MarkerFaceColor', rgb('Yellow'), ...
    'MarkerEdgeColor', 'k', 'MarkerSize', 15)
plot(poissWords(3), neuralWords(3), 'o', 'MarkerFaceColor', rgb('Green'), ...
    'MarkerEdgeColor', 'k', 'MarkerSize', 15)
xlabel('Poisson'); ylabel('Neural'); title('Words')
box off; axis square;
rf = refline(1,0); rf.Color = rgb('DarkGrey'); rf.LineStyle = '--'; rf.LineWidth = 1;

